### ISSUE TITLE
(Very) Minor Changes

### ISSUE THREAD

**Issue by KrisNguyen135** [DPUDS/DPUDS_Meetings#8]
1) P(R \cap G) should be 0.1 after "We know that..." line.
2) "being the predicting" after In [74] should be "begin the predicting"

Please update the file for me. The reason I didn't send a pull request is when I ran the notebook on my local machine, the line that displays the picture gave me an error because I don't have the specified picture. So if my pull request was merged, the notebook file on DPUDS would also display the error.

On that note, I didn't know about the image display function from IPython - pretty cool. You might have noticed that I usually use the "![alt text](url)" code to display a hosted picture in Markdown, which I think could be beneficial for us in this case, because if we were to run each other's notebook on our local machine, it would not give the "Image not found" error.

That aside, awesome tutorial. I myself didn't know about the classifier, so it was a learning experience for me.

Be sure to close this issue when you finish updating the file.

**Comment by KrisNguyen135** [comment]
Just realized the sample code to include an image was rendered by GitHub... [Here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images) is the link to the function I tried to illustrate.

**Comment by DPUDS** [comment]
Issue is resolved except for the typo. Fixing now.

**Comment by DPUDS** [comment]
Fixed
